
name: Create PR to plugins
on:
  workflow_dispatch:
jobs:
  create_pr:
    name: Create PR to plugins
    runs-on: ubuntu-latest
    permissions: { pull-requests: write, contents: write }
    steps:
      - uses: actions/checkout@v3
      - name: Create PR
        env: { GITHUB_TOKEN: "${{ github.token }}" }
        run: |
          wget https://github.com/pragtical/plugin-manager/releases/download/continuous/ppm.x86_64-linux -O ppm && chmod +x ppm &&
            ./ppm --plugin gh.lua gh create-addon-update-pr
